package residentevm

import ("bytes"; "crypto/sha256"; "encoding/binary"; "errors")

const ( WireVersion uint16 = 1; SchemaVersion uint16 = 1; MaxFramePayload = 1 << 20; MaxAggregatePayload = 4 << 20; MaxChunkCount uint32 = 4096 )
var frameMagic = [8]byte{'R','H','C','E','V','M','0','1'}
type Frame struct { WireVersion uint16; SchemaVersion uint16; FeatureBits uint32; Flags uint32; LogicalSequence uint64; TransportSequence uint64; ChunkIndex uint32; ChunkCount uint32; GapEpoch uint64; Payload []byte }
const frameHeaderSize = 8 + 2 + 2 + 4 + 4 + 8*3 + 4*3 + 32 + 4
func validateFrameMeta(f Frame) error { if f.WireVersion != WireVersion || f.SchemaVersion != SchemaVersion { return errors.New("unsupported frame version") }; if f.ChunkCount == 0 || f.ChunkCount > MaxChunkCount || f.ChunkIndex >= f.ChunkCount { return errors.New("invalid frame bounds") }; if len(f.Payload) > MaxFramePayload { return errors.New("frame payload too large") }; return nil }
func EncodeFrame(f Frame) ([]byte,error) { if err:=validateFrameMeta(f);err!=nil{return nil,err}; h:=sha256.Sum256(f.Payload); out:=make([]byte,frameHeaderSize+len(f.Payload)); copy(out[:8],frameMagic[:]); p:=8; binary.BigEndian.PutUint16(out[p:],f.WireVersion);p+=2;binary.BigEndian.PutUint16(out[p:],f.SchemaVersion);p+=2;binary.BigEndian.PutUint32(out[p:],f.FeatureBits);p+=4;binary.BigEndian.PutUint32(out[p:],f.Flags);p+=4;binary.BigEndian.PutUint64(out[p:],f.LogicalSequence);p+=8;binary.BigEndian.PutUint64(out[p:],f.TransportSequence);p+=8;binary.BigEndian.PutUint64(out[p:],f.GapEpoch);p+=8;binary.BigEndian.PutUint32(out[p:],f.ChunkIndex);p+=4;binary.BigEndian.PutUint32(out[p:],f.ChunkCount);p+=4;binary.BigEndian.PutUint32(out[p:],uint32(len(f.Payload)));p+=4;copy(out[p:p+32],h[:]);p+=32;copy(out[p:],f.Payload);binary.BigEndian.PutUint32(out[p+len(f.Payload):],crc32c(out[:p+len(f.Payload)]));return out,nil }
func DecodeFrame(data []byte)(Frame,error){if len(data)<frameHeaderSize||!bytes.Equal(data[:8],frameMagic[:]){return Frame{},errors.New("invalid frame header")};p:=8;f:=Frame{WireVersion:binary.BigEndian.Uint16(data[p:])};p+=2;f.SchemaVersion=binary.BigEndian.Uint16(data[p:]);p+=2;f.FeatureBits=binary.BigEndian.Uint32(data[p:]);p+=4;f.Flags=binary.BigEndian.Uint32(data[p:]);p+=4;f.LogicalSequence=binary.BigEndian.Uint64(data[p:]);p+=8;f.TransportSequence=binary.BigEndian.Uint64(data[p:]);p+=8;f.GapEpoch=binary.BigEndian.Uint64(data[p:]);p+=8;f.ChunkIndex=binary.BigEndian.Uint32(data[p:]);p+=4;f.ChunkCount=binary.BigEndian.Uint32(data[p:]);p+=4;n:=binary.BigEndian.Uint32(data[p:]);p+=4;if err:=validateFrameMeta(Frame{WireVersion:f.WireVersion,SchemaVersion:f.SchemaVersion,ChunkIndex:f.ChunkIndex,ChunkCount:f.ChunkCount,Payload:make([]byte,n)});err!=nil{return Frame{},err};if uint64(n)>uint64(len(data)-p-36)||len(data)!=p+32+int(n)+4{return Frame{},errors.New("invalid frame length")};want:=data[p:p+32];p+=32;f.Payload=append([]byte(nil),data[p:p+int(n)]...);got:=sha256.Sum256(f.Payload);if !bytes.Equal(want,got[:])||binary.BigEndian.Uint32(data[p+int(n):])!=crc32c(data[:p+int(n)]){return Frame{},errors.New("frame checksum mismatch")};return f,nil}
func crc32c(data []byte)uint32{var crc uint32=0xffffffff;for _,b:=range data{crc^=uint32(b);for i:=0;i<8;i++{mask:=uint32(0)-(crc&1);crc=(crc>>1)^(0x82f63b78&mask)}};return ^crc}
func ReassembleFrames(frames [][]byte)([]byte,error){if len(frames)==0||len(frames)>int(MaxChunkCount){return nil,errors.New("invalid frame set")};decoded:=make([]Frame,len(frames));total:=0;for i,b:=range frames{f,e:=DecodeFrame(b);if e!=nil{return nil,e};decoded[i]=f;total+=len(f.Payload);if total>MaxAggregatePayload{return nil,errors.New("aggregate payload too large")}};first:=decoded[0];if first.ChunkCount!=uint32(len(frames)){return nil,errors.New("incomplete chunk set")};out:=make([][]byte,len(frames));for _,f:=range decoded{if f.ChunkCount!=first.ChunkCount||f.LogicalSequence!=first.LogicalSequence||f.TransportSequence!=first.TransportSequence||f.GapEpoch!=first.GapEpoch{return nil,errors.New("chunk identity mismatch")};if out[f.ChunkIndex]!=nil{return nil,errors.New("duplicate chunk")};out[f.ChunkIndex]=f.Payload};joined:=make([]byte,0,total);for _,p:=range out{if p==nil{return nil,errors.New("missing chunk")};joined=append(joined,p...)};return joined,nil}
